<?php

/**
 * @file
 * ECC Parents module hooks.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Set service contacts from parent page if not already set.
 *
 * Also set service contacts on guide pages if overview page updated.
 *
 * Scenarios:
 * Guide overview old values: paul, mary
 * changed to
 * new values: john, pat
 *
 * Match old: paul, mary -> john,pat (replace)
 * Match new: john, pat -> john, pat (replace/no change)
 * Partial match: paul, sile -> john, sile, pat (remove & copy)
 * No match: frances -> frances, john, pat (copy)
 */
function ecc_parents_node_presave(EntityInterface $entity) {
  // Set guide page contacts based upon parent.
  /** @var \Drupal\node\NodeInterface $entity */

  // Add other content types, when required.
  $content_types = ['localgov_guides_page'];

  if (in_array($entity->bundle(), $content_types)) {
    /** @var \Drupal\ecc_parents\Parents $parents_service */
    $parents_service = \Drupal::service('ecc_parents.parents');
    $service_contact = $entity->get('localgov_service_contacts')
      ?->referencedEntities();
    if (empty($service_contact)) {
      if ($parent = $parents_service->getParent($entity)) {
        $parent_service_contacts = $parent->get('localgov_service_contacts')
          ->getValue();
        if ($parent_service_contacts) {
          $entity->set('localgov_service_contacts', $parent_service_contacts);
        }
      }
    }
  }

  // Update pages based on changes to overview.
  if ($entity->bundle() === 'localgov_guides_overview') {
    // Cascade is default behaviour unless editors turn it off.
    $cascade_contacts = TRUE;
    // Check for a switch for editor choice.
    // If the field isn't there, default behaviour kicks in.
    if ($entity->hasField('field_guide_cascade_contacts')) {

      if (!empty($entity->get('field_guide_cascade_contacts')->value)) {
        $cascade_contacts = TRUE;
      }
      else {
         $cascade_contacts = FALSE;
      }
    }
    if ($cascade_contacts) {
      $new_service_contacts = $entity->get('localgov_service_contacts')
      ?->referencedEntities();
      $old_service_contacts = $entity->original->get('localgov_service_contacts')
        ?->referencedEntities();
      if ($old_service_contacts === $new_service_contacts) {
        // Service contacts are unchanged: nothing to update.
      }
      else {
        // We'll need to bail if there's no child pages field.
        if ($entity->hasField('localgov_guides_pages')) {
          // Get all children.
          $child_pages = $entity->get('localgov_guides_pages')?->referencedEntities();
          if (!empty($child_pages)) {
            // Iterate over children.
            foreach ($child_pages as $child_page) {
              // For each child, get service contacts.
              $child_contacts = $child_page->get('localgov_service_contacts')
          ?->referencedEntities();
              // For each old contact, remove from child contacts.
              if (!empty($child_contacts)) {
                foreach ($old_service_contacts as $i => $old_contact) {
                  foreach ($child_contacts as $child_contact) {
                    if ($child_contact->id() === $old_contact->id()) {
                      // Remove the old contact from the child node.
                      unset($child_contacts[$i]);
                    }
                  }
                }
              }
              else {
                $child_contacts = [];
              }
              // Add new contacts.
              $new_child_contacts = array_merge($child_contacts, $new_service_contacts);

              $unique_contacts = [];
              $seen_ids = [];
              foreach ($new_child_contacts as $new_child_contact) {
                $id = $new_child_contact->id();
                if (!in_array($id, $seen_ids)) {
                  $seen_ids[] = $id;
                  $unique_contacts[] = $new_child_contact;
                }
              }
              $new_child_contacts = $unique_contacts;

              // Save.
              $child_page->set('localgov_service_contacts', $new_child_contacts);
              $child_page->save();
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * When a page is published/unpublished then do the same for its children.
 *
 * Beware of loops! It doesn't look like it's a problem but saving a guide page
 * could try to save the overview again.
 *
 * @see \Drupal\localgov_guides\ChildParentRelationship
 */
function ecc_parents_node_update(EntityInterface $entity) {
  /** @var \Drupal\node\NodeInterface $entity */

  // Add other content types, when required.
  $content_types = ['localgov_guides_overview'];

  if (in_array($entity->bundle(), $content_types)) {
    /** @var \Drupal\ecc_parents\Parents $parents_service */
    $parents_service = \Drupal::service('ecc_parents.parents');

    if (!$entity->original->isPublished() && $entity->isPublished()) {
      foreach ($parents_service->getChildren($entity) as $child) {
        if (!$child->isPublished() && $child->field_publish_with_parent->value) {
          $child->setPublished();
          $child->set('moderation_state', 'published');
          $child->save();
        }
      }
    }
    elseif ($entity->original->isPublished() && !$entity->isPublished()) {
      foreach ($parents_service->getChildren($entity) as $child) {
        if ($child->isPublished() && $child->field_publish_with_parent->value) {
          $child->setUnpublished();
          $child->set('moderation_state', 'archived');
          $child->save();
        }
      }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Move field_publish_with_parent next to published state.
 */
function ecc_parents_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['field_publish_with_parent']) && isset($form['advanced'])) {
    $form['field_publish_with_parent']['#group'] = 'footer';
  }
  $nid = $form_state->getformObject()->getEntity()->id();
  if (isset($nid) && !empty($nid)) {
    $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
    $parents_service = \Drupal::service('ecc_parents.parents');
    $children = $parents_service->getChildren($node);
    if (!empty($children)) {
      $form['#attached']['library'][] = 'ecc_parents/node.form';
    }
  }
}

/**
 * Implements hook_views_pre_build().
 *
 * Copy value of exposed form element to hidden parameters. This allows filter
 * to work for content types with different parent field.
 */
function ecc_parents_views_pre_build(ViewExecutable $view) {
  if ($view->id() === 'parents') {
    $request = $view->getRequest();
    $parameters = $request->query;
    $parent = $parameters->get('parent');
    $request->query->set('guide_parent', $parent);
    $request->query->set('step_parent', $parent);
    $view->setRequest($request);
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ecc_parents_views_pre_render(ViewExecutable $view) {
  if ($view->id() === 'parents') {
    $view->element['#attached']['library'][] = 'ecc_parents/views';
  }
}

/**
 * Implements hook_views_data().
 */
function ecc_parents_views_data() {
  $data['node']['nid'] = [
    'title' => t('ECC Parent'),
    'help' => t('Parent page for any ECC (LGD) content type.'),
    'field' => [
      'id' => 'ecc_parents_views_field',
    ],
  ];

  return $data;
}
